### ISSUE TITLE
Exception in IDEA log

### ISSUE THREAD

**Issue by tanmatra** [vsch/touch-typists-completion-caddy#1]
And the file really have zero size.

```
2020-09-21 10:07:27,317 [   6393]   INFO - m.intellij.util.lang.ClassPath - url: file:/C:/Users/Roman/AppData/Roaming/JetBrains/IntelliJIdea2020.2/plugins/TouchTypistsCompletionCaddy/lib/flexmark-tree-iteration.jar 
java.util.zip.ZipException: zip file is empty
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1567)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1375)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1469)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:148)
	at com.intellij.util.lang.JarLoader.createZipFile(JarLoader.java:318)
	at com.intellij.util.lang.JarLoader.getZipFile(JarLoader.java:308)
	at com.intellij.util.lang.JarLoader.<init>(JarLoader.java:53)
	at com.intellij.util.lang.ClassPath.createLoader(ClassPath.java:224)
	at com.intellij.util.lang.ClassPath.initLoaders(ClassPath.java:211)
	at com.intellij.util.lang.ClassPath.getLoaderSlowPath(ClassPath.java:164)
	at com.intellij.util.lang.ClassPath.getLoader(ClassPath.java:143)
	at com.intellij.util.lang.ClassPath.getResource(ClassPath.java:111)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:364)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:258)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:204)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:93)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:423)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:408)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:369)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:258)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:204)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:93)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:287)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:193)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:157)
	at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:102)
	at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt:390)
	at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
	at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:387)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.a.a(a.java:106)
	at com.intellij.ide.a.l.ab.a(ab.java:91)
	at com.intellij.ide.a.l.S.b(S.java:276)
	at com.intellij.ide.a.l.T.b(T.java:307)
	at com.intellij.ide.a.l.T.c(T.java:167)
	at com.intellij.ide.a.l.T.a(T.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.MainImpl.start(MainImpl.java:98)
	at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:302)
	at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:242)
	at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:47)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by falleng0d** [comment]
I'm getting a similar error message on 2021.1.2

```
Plugin 'com.vladsch.plugins.touchTypistsCompletionCaddy' failed to initialize and will be disabled. Please restart PhpStorm.

java.io.UncheckedIOException: java.util.zip.ZipException: Archive is not a ZIP archive
    at com.intellij.util.lang.ZipResourceFile.<init>(ZipResourceFile.java:42)
    at com.intellij.util.lang.PathClassLoader.lambda$static$0(PathClassLoader.java:15)
    at com.intellij.util.lang.ClassPath.createLoader(ClassPath.java:391)
    at com.intellij.util.lang.ClassPath.getLoaderSlowPath(ClassPath.java:338)
    at com.intellij.util.lang.ClassPath.getLoader(ClassPath.java:319)
    at com.intellij.util.lang.ClassPath.findClass(ClassPath.j{a}va:199)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:338)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:233)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:212)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at java.base/java.lang.ClassLoader.defineClass2(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1109)
    at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:269)
    at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:121)
    at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:55)
    at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:221)
    at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:204)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:338)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:233)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:212)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:398)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:368)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:316)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:254)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:106)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
    at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
    at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
    at com.intellij.idea.ApplicationLoader.registerAppComponents(ApplicationLoader.kt:104)
    at com.intellij.idea.ApplicationLoader.executeInitAppInEdt(ApplicationLoader.kt:63)
    at com.intellij.idea.ApplicationLoader.access$executeInitAppInEdt(ApplicationLoader.kt:1)
    at com.intellij.idea.ApplicationLoader$initApplication$1$1.run(ApplicationLoader.kt:363)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.util.zip.ZipException: Archive is not a ZIP archive
    at com.intellij.util.zip.ImmutableZipFile.readEndSignature(ImmutableZipFile.java:234)
    at com.intellij.util.zip.ImmutableZipFile.populateFromCentralDirectory(ImmutableZipFile.java:119)
    at com.intellij.util.zip.ImmutableZipFile.load(ImmutableZipFile.java:74)
    at com.intellij.util.lang.ZipResourceFile.<init>(ZipResourceFile.java:36)
    ... 47 m
```

**Comment by vsch** [comment]
New build out for 2020.3+ compatibility. This issue no longer applies.
